


















function PageTransitions(){const t=$("#pages"),n={front:0,right:-90,back:180,left:90,bottom:270},e=()=>{let n=t[0].style.transform.match(/-?\d+/g)||0;return n=0!==n?parseInt(n[0]):0},o=n=>{t.velocity({rotateY:[n]},{duration:2e3,easing:"easeOut"})};return{change:n=>{let i=t.attr("class"),a=1===n?-360:360,c=1===n?90:-90;if(!i){let n=e();n===a?t.velocity({rotateY:[0]},{duration:0,complete:()=>{n=e(),o(n+c)}}):o(n+c)}},move:t=>{o(n[t])}}}function Navigation(t){const n=$("nav"),e=n.find("#buttons"),o=n.find("#menu"),i=e.find(".buttons-navi"),a=i.find(".button:nth-child(1)"),c=i.find(".button:nth-child(2)"),r=c.find(".button-next"),s=a.find(".button-prev"),d=e.find(".buttons-menu .button"),l=o.find("li"),u=d.find(".button-wrapper"),f=u.find("span:nth-child(1)"),v=u.find("span:nth-child(2)"),h=u.find("span:nth-child(3)"),p=[f,v,h],g=t=>{const n=()=>{t(),window.removeEventListener("unload",n)};window.addEventListener("unload",n)},b=()=>{f.velocity({rotateZ:"135deg",top:"12px"},{duration:300}),v.velocity({right:"40px",opacity:0},{duration:300}),h.velocity({rotateZ:"-135deg",top:"12px"},{duration:300})},w=()=>{p.forEach(t=>{t.velocity("reverse")})},m=()=>{i.hide(),o.show(),o.velocity({translateY:[0,-180],scale:[1,0],opacity:[1,0]},{duration:1e3})},y=()=>{i.show(),o.velocity("reverse",{duration:1e3,easing:"spring",complete:()=>{o.hide()}})},k=()=>{let t=200;l.each((n,e)=>{let o=$(e);o.show(),o.velocity({translateX:["0vw","-100vw"],backgroundColorAlpha:[0,1]},{duration:1e3,delay:t}),t+=200})},E=[w,y,t.move];return{animateChangePageButton:()=>{const t=t=>{t.data.object.velocity({scale:[1,0]},{duration:1e3,easing:"spring"})};c.on("mouseenter",{object:r},t),g(()=>{c.off("mouseenter",t)}),a.on("mouseenter",{object:s},t),g(()=>{a.off("mouseenter",t)})},nextPage:()=>{const n=e.find(".buttons-navi .button:nth-child(2)"),o=()=>{t.change(0)};n.on("click",o),g(()=>{n.off("click",o)})},prevPage:()=>{const n=e.find(".buttons-navi .button:nth-child(1)"),o=()=>{t.change(1)};n.on("click",o),g(()=>{n.off("click",o)})},menuButtonClick:()=>{const t=()=>{o.attr("class")||(1===parseInt(v.css("opacity"))?[b,m,k].forEach(t=>{t()}):[w,y].forEach(t=>{t()}))};d.on("click",t),g(()=>{d.off("click",t)})},menuItemClick:()=>{l.each((t,n)=>{let e=$(n);e.on("click",()=>{(t=>{E.forEach(n=>{n(t)})})(e[0].id)}),g(()=>{e.off("click")})})}}}function Apx(t,n){const e=new t(new n);return{init:()=>{Object.values(e).forEach(t=>{(t=>{const n=()=>{window.removeEventListener("DOMContentLoaded",t),window.removeEventListener("unload",n)};window.addEventListener("DOMContentLoaded",t),window.addEventListener("unload",n)})(t)})}}}$("#aboutbutton").click(()=>{$("#pages").velocity({rotateY:[180]},{duration:2e3,easing:"easeOut"})});const app=new Apx(Navigation,PageTransitions);app.init();
